config/routes.rb
Collectiveopus::Application.routes.draw do
  get "home/index"

  resources :gifts

  resources :projects

  resources :collectives

  resources :users

  root :to => 'home#index', as: 'home'

end

app/models/collective.rb
class Collective < ActiveRecord::Base
  belongs_to :user
  has_many :projects
  has_many :users
  
  before_destroy :ensure_not_referenced_by_any_project
  attr_accessible :collective_id, :collective_name, :user_id

  private
  def ensure_not_referenced_by_any_project
  	if projects.empty?
  		return true
  	else
  		errors.add(:base, 'Projects still ongoing')
  		return false
  	end
  end

end

app/controllers/collectives_controller.rb
class CollectivesController < ApplicationController
  # GET /collectives
  # GET /collectives.json
  def index
    @collectives = Collective.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @collectives }
    end
  end

  # GET /collectives/1
  # GET /collectives/1.json
  def show
    @collective = Collective.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @collective }
    end
  end

  # GET /collectives/new
  # GET /collectives/new.json
  def new
    @collective = Collective.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @collective }
    end
  end

  # GET /collectives/1/edit
  def edit
    @collective = Collective.find(params[:id])
  end

  # POST /collectives
  # POST /collectives.json
  def create
    @collective = Collective.new(params[:collective])

    respond_to do |format|
      if @collective.save
        format.html { redirect_to @collective, notice: 'Collective was successfully created.' }
        format.json { render json: @collective, status: :created, location: @collective }
      else
        format.html { render action: "new" }
        format.json { render json: @collective.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /collectives/1
  # PUT /collectives/1.json
  def update
    @collective = Collective.find(params[:id])

    respond_to do |format|
      if @collective.update_attributes(params[:collective])
        format.html { redirect_to @collective, notice: 'Collective was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @collective.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collectives/1
  # DELETE /collectives/1.json
  def destroy
    @collective = Collective.find(params[:id])
    @collective.destroy

    respond_to do |format|
      format.html { redirect_to collectives_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/collectives_helper.rb
module CollectivesHelper
end

app/views/collectives/_form.html.erb
<%= form_for(@collective) do |f| %>
  <% if @collective.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collective.errors.count, "error") %> prohibited this collective from being saved:</h2>

      <ul>
      <% @collective.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :collective_id %><br />
    <%= f.number_field :collective_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :collective_name %><br />
    <%= f.text_field :collective_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collectives/edit.html.erb
<h1>Editing collective</h1>

<%= render 'form' %>

<%= link_to 'Show', @collective %> |
<%= link_to 'Back', collectives_path %>

app/views/collectives/index.html.erb
<h1>Listing collectives</h1>

<table>
  <tr>
    <th>Collective</th>
    <th>User</th>
    <th>Collective name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @collectives.each do |collective| %>
  <tr>
    <td><%= collective.collective_id %></td>
    <td><%= collective.user_id %></td>
    <td><%= collective.collective_name %></td>
    <td><%= link_to 'Show', collective %></td>
    <td><%= link_to 'Edit', edit_collective_path(collective) %></td>
    <td><%= link_to 'Destroy', collective, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Collective', new_collective_path %>

app/views/collectives/new.html.erb
<h1>New collective</h1>

<%= render 'form' %>

<%= link_to 'Back', collectives_path %>

app/views/collectives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Collective:</b>
  <%= @collective.collective_id %>
</p>

<p>
  <b>User:</b>
  <%= @collective.user_id %>
</p>

<p>
  <b>Collective name:</b>
  <%= @collective.collective_name %>
</p>


<%= link_to 'Edit', edit_collective_path(@collective) %> |
<%= link_to 'Back', collectives_path %>