config/routes.rb
Collectiveopus::Application.routes.draw do
  get "home/index"

  resources :gifts

  resources :projects

  resources :collectives

  resources :users

  root :to => 'home#index', as: 'home'

end

app/models/gift.rb
class Gift < ActiveRecord::Base
  belongs_to :project
  attr_accessible :gift_id, :gift_name, :gift_url, :project_id
  
  validates :gift_name, :gift_url, :presence => true
  validates :gift_name, :uniqueness => true
  validates :gift_url, :allow_blank => true, 
	:format => {
		with: %r{\.|gif|jpg|png|\Z}i,
		
		:message => 'Must be a URL for an image file for GIF, JPG and PNG.'
	}
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  # GET /gifts
  # GET /gifts.json
  def index
    @gifts = Gift.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gifts }
    end
  end

  # GET /gifts/1
  # GET /gifts/1.json
  def show
    @gift = Gift.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gift }
    end
  end

  # GET /gifts/new
  # GET /gifts/new.json
  def new
    @gift = Gift.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gift }
    end
  end

  # GET /gifts/1/edit
  def edit
    @gift = Gift.find(params[:id])
  end

  # POST /gifts
  # POST /gifts.json
  def create
    @gift = Gift.new(params[:gift])

    respond_to do |format|
      if @gift.save
        format.html { redirect_to @gift, notice: 'Gift was successfully created.' }
        format.json { render json: @gift, status: :created, location: @gift }
      else
        format.html { render action: "new" }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gifts/1
  # PUT /gifts/1.json
  def update
    @gift = Gift.find(params[:id])

    respond_to do |format|
      if @gift.update_attributes(params[:gift])
        format.html { redirect_to @gift, notice: 'Gift was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifts/1
  # DELETE /gifts/1.json
  def destroy
    @gift = Gift.find(params[:id])
    @gift.destroy

    respond_to do |format|
      format.html { redirect_to gifts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/views/gifts/_form.html.erb
<%= form_for(@gift) do |f| %>
  <% if @gift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gift.errors.count, "error") %> prohibited this gift from being saved:</h2>

      <ul>
      <% @gift.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :gift_id %><br />
    <%= f.number_field :gift_id %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.number_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :gift_name %><br />
    <%= f.text_field :gift_name %>
  </div>
  <div class="field">
    <%= f.label :gift_url %><br />
    <%= f.text_field :gift_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gifts/edit.html.erb
<h1>Editing gift</h1>

<%= render 'form' %>

<%= link_to 'Show', @gift %> |
<%= link_to 'Back', gifts_path %>

app/views/gifts/index.html.erb
<h1>Listing gifts</h1>

<table>
  <tr>
    <th>Gift</th>
    <th>Project</th>
    <th>Gift name</th>
    <th>Gift url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @gifts.each do |gift| %>
  <tr class="<%= cycle('gift_line_odd', 'gift_line_even') %>">
    <td><%= gift.gift_id %></td>
    <td><%= gift.project_id %></td>
    <td><%= gift.gift_name %></td>
    <td><%= gift.gift_url %></td>
    <td><%= link_to 'Info', gift %></td>
    <td><%= link_to 'Edit', edit_gift_path(gift) %></td>
	<td><%= link_to 'Download', gift %></td>
    <td><%= link_to 'Destroy', gift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gift', new_gift_path %>

app/views/gifts/new.html.erb
<h1>New gift</h1>

<%= render 'form' %>

<%= link_to 'Back', gifts_path %>

app/views/gifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Gift:</b>
  <%= @gift.gift_id %>
</p>

<p>
  <b>Project:</b>
  <%= @gift.project_id %>
</p>

<p>
  <b>Gift name:</b>
  <%= @gift.gift_name %>
</p>

<p>
  <b>Gift url:</b>
  <%= @gift.gift_url %>
</p>


<%= link_to 'Edit', edit_gift_path(@gift) %> |
<%= link_to 'Back', gifts_path %>